services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: quest-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Quest_dev_2026!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - quest-sqlserver-data:/var/opt/mssql
      - ./database:/database:ro
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 20
      start_period: 20s

volumes:
  quest-sqlserver-data:
